return {
  fg = "#dcdccc", -- Normal foreground
  bg = "#18181b", -- Normal background
  dark = "#121212", -- Dark areas from CursorLine background
  accent = "#ffa263", -- Accent color common in the theme
  popup_back = "#2e3330", -- Popup background from PmenuSbar
  search_orange = "#ffa263", -- Orange color common in the theme
  search_blue = "#5e81ac", -- Adjusted to match Vimscript search blue
  gray = "#808080", -- Adjusted for consistency with Vimscript general gray
  dark_gray = "#333333", -- Darker areas like DiffDelete background
  context = "#606060", -- Adjusted to more closely match Vimscript context
  light_gray = "#c8c9c1", -- Light gray used in various text elements
  blue = "#569CD6", -- Adjusted to match Vimscript blue for clarity
  dark_blue = "#223E55", -- Dark blue for deeper background elements
  light_blue = "#9CDCFE", -- Light blue for highlights and cursors
  cyan = "#4EC9B0", -- Adjusted to match Vimscript cyan
  green = "#6A9955", -- Adjusted to match Vimscript green
  light_green = "#B5CEA8", -- Light green for diff and other highlights
  red = "#F44747", -- Adjusted vibrant red for errors and warnings
  light_red = "#D16969", -- Light red for less intense error indicators
  orange = "#CE9178", -- Adjusted to better match Vimscript orange
  yellow = "#DCDCAA", -- Adjusted bright yellow for attention-grabbing text
  yellow_orange = "#D7BA7D", -- A blend of yellow and orange for specific highlights
  purple = "#C586C0", -- Soft purple adjusted to match Vimscript settings
  magenta = "#D16D9E", -- Magenta for more vivid highlights
  cursor_fg = "#515052", -- Cursor text color for better visibility
  cursor_bg = "#AEAFAD", -- Cursor background for subtle visibility
  error_red = "#F44747", -- Bright red for critical errors
  warning_orange = "#ff8800", -- Vibrant orange for warnings
  info_yellow = "#FFCC66", -- Information yellow for less critical highlights
  hint_blue = "#4FC1FF", -- Blue for hints and subtle notifications
  ui_blue = "#264F78", -- UI blue for status lines and more subtle elements
  diff_add = "#587c0c", -- Green for added lines in diff
  diff_change = "#0c7d9d", -- Blue for changed lines
  diff_delete = "#94151b", -- Red for deleted lines
  diff_text = "#265478", -- Dark blue for text within diff sections
}
