return {
  fg = "#dcdccc", -- Foreground color for regular text
  bg = "#18181b", -- Background color for the editor
  dark = "#121212", -- Dark background for focused items like cursor lines
  accent = "#ffa263", -- Accent color for variables and types
  popup_back = "#2e3330", -- Background color for popup menus
  search_orange = "#ffa263", -- Color for highlighted search results
  search_blue = "#5e81ac", -- Secondary color for highlighted search results
  gray = "#808080", -- Gray color for non-essential UI elements
  dark_gray = "#333333", -- Dark gray for UI elements requiring contrast
  context = "#606060", -- Color for less prominent text, like line numbers
  light_gray = "#c8c9c1", -- Light gray for inactive text and borders
  blue = "#569CD6", -- Blue color for keywords and links
  dark_blue = "#223E55", -- Dark blue for deep background areas
  light_blue = "#9CDCFE", -- Light blue for active text and cursor highlights
  cyan = "#4EC9B0", -- Cyan color for interface elements and selections
  green = "#6A9955", -- Green color for comments and strings
  light_green = "#B5CEA8", -- Light green for diffs and modified text highlights
  red = "#F44747", -- Red for errors and critical warnings
  light_red = "#D16969", -- Light red for warnings and minor errors
  orange = "#CE9178", -- Orange for meta tags and attributes
  yellow = "#DCDCAA", -- Yellow for functions and methods
  yellow_orange = "#D7BA7D", -- Blend of yellow and orange for special tokens
  purple = "#C586C0", -- Purple for constants and macros
  magenta = "#D16D9E", -- Magenta for commands and important tags
  cursor_fg = "#515052", -- Foreground color of the cursor
  cursor_bg = "#AEAFAD", -- Background color of the cursor
  error_red = "#F44747", -- Bright red for critical errors
  warning_orange = "#ff8800", -- Vibrant orange for warning messages
  info_yellow = "#FFCC66", -- Bright yellow for informational messages
  hint_blue = "#4FC1FF", -- Soft blue for hints and informational text
  ui_blue = "#264F78", -- Dark blue for UI elements and status bars
  diff_add = "#587c0c", -- Color for added lines in diffs
  diff_change = "#0c7d9d", -- Color for changed lines in diffs
  diff_delete = "#94151b", -- Color for deleted lines in diffs
  diff_text = "#265478", -- Highlight color within changed lines in diffs
  string_color = "#ffc1c1", -- Color for string literals
  func_color = "#ffd787", -- Color for functions and methods
  special_char = "#dca3a3", -- Color for special characters
  identifier_color = "#efdcbc", -- Color for identifiers and labels
  debug_color = "#bca3a3", -- Color used for debugging markers
  special_comment = "#82a282", -- Color for special comments
  special_key = "#9ece9e", -- Color for special keys and shortcuts
  folded_color = "#93b3a3", -- Color for folded sections
  error_msg_bg = "#2f2f2f", -- Background color for error messages
  mode_msg = "#ffcfaf", -- Color for mode messages and status information
  preproc_color = "#dfaf8f", -- Color for preprocessor directives
  directory_fg = "#9fafaf", -- Foreground color for directories
  inc_search_bg = "#385f38", -- Background color for incremental search
}
