return {
  fg = "#dcdccc", -- Normal foreground
  bg = "#18181b", -- Normal background
  dark = "#121212", -- Dark areas from CursorLine background
  accent = "#ffa263", -- Accent color common in the theme
  popup_back = "#2e3330", -- Popup background from PmenuSbar
  search_orange = "#ffa263", -- Orange color common in the theme
  search_blue = "#93b3a3", -- Folded background, a calmer shade of blue-green
  gray = "#8f8f8f", -- Delimiter color
  dark_gray = "#333333", -- Darker areas like DiffDelete background
  context = "#999999", -- LineNr foreground
  light_gray = "#ccccbc", -- Pmenu foreground
  blue = "#8cd0d3", -- Used for Number foreground, a soft blue
  dark_blue = "#1f1f1e", -- A darker tone close to the background
  light_blue = "#93b3a3", -- Soft light blue used in Folded background
  cyan = "#8faf9f", -- Cursor background, a cyan-like color
  green = "#afd8af", -- A softer green, for success or valid items
  light_green = "#9ece9e", -- SpecialKey foreground, a light green
  red = "#ff5f5f", -- A vibrant red for errors
  light_red = "#ffafaf", -- A lighter red used for DiffText
  orange = "#ffaf87", -- A soft orange, close to DiffText background
  yellow = "#ffffaf", -- A bright yellow for attention
  yellow_orange = "#ffd787", -- Conditional foreground, a yellow-orange
  purple = "#d787af", -- Define foreground, a soft purple
  magenta = "#d75f87", -- Magenta closer to the red side
  cursor_fg = "#000d18", -- Cursor foreground, a very dark blue
  cursor_bg = "#8faf9f", -- Cursor background, a cyan-like color
  error_red = "#ff5f5f", -- A bright red for critical errors
  warning_orange = "#ffaf5f", -- Orange for warnings, lighter than error red
  info_yellow = "#ffd787", -- A light yellow-orange used for information
  hint_blue = "#9ece9e", -- A light green-blue, soothing for hints
  ui_blue = "#83af9b", -- UI elements, a muted blue-green
  diff_add = "#709080", -- DiffAdd foreground, a muted green
  diff_change = "#8f8f8f", -- DiffChange foreground, neutral gray
  diff_delete = "#9f5f5f", -- DiffDelete foreground, a rusty red
  diff_text = "#ecbcbc", -- DiffText foreground, a pale pink
}
