local c = require("stardust.colors")
local config = require("stardust.config")

local M = {}

M.base = {
  Bold = { style = "bold" },
  Italic = { style = "italic" },
  Underlined = { style = "underline" },

  Boolean = { fg = c.orange, style = "bold" },
  Character = { fg = c.red },
  ColorColumn = { bg = c.popup_back },
  Comment = { fg = c.gray, style = "italic" },
  Conceal = { fg = c.accent, bg = config.transparent_background and "NONE" or c.bg },
  Conditional = { fg = c.purple, style = "bold" },
  Constant = { fg = c.orange, style = "bold" },
  Cursor = { fg = c.cursor_fg, bg = c.cursor_bg, style = "bold" },
  CursorColumn = { bg = c.dark },
  CursorIM = { fg = c.cursor_fg, bg = c.cursor_bg },
  CursorLine = { bg = c.dark },
  CursorLineNr = { fg = c.light_gray, style = "bold" },
  Debug = { fg = c.red },
  Define = { fg = c.purple },
  Delimiter = { fg = c.gray },
  DiffAdd = { fg = c.green, bg = c.dark },
  DiffChange = { fg = c.yellow, bg = c.dark },
  DiffDelete = { fg = c.red, bg = c.dark },
  DiffText = { fg = c.blue, bg = c.dark },
  Directory = { fg = c.blue },
  EndOfBuffer = { fg = c.bg },
  Error = { fg = c.red, bg = c.dark, style = "bold" },
  ErrorMsg = { fg = c.error_fg, bg = c.error_bg, style = "bold" },
  Exception = { fg = c.purple },
  Float = { fg = c.blue },
  FloatBorder = { fg = c.gray, bg = c.dark },
  FoldColumn = { fg = c.accent, bg = c.dark },
  Folded = { fg = c.accent, bg = c.dark },
  Function = { fg = c.blue },
  Identifier = { fg = c.fg },
  IncSearch = { fg = c.yellow, bg = c.dark },
  Include = { fg = c.purple },
  Keyword = { fg = c.purple, style = "bold" },
  Label = { fg = c.blue },
  LineNr = { fg = c.gray },
  Macro = { fg = c.red },
  MatchParen = { fg = c.blue, bg = c.dark, style = "bold" },
  ModeMsg = { fg = c.fg },
  MoreMsg = { fg = c.orange },
  MsgArea = { fg = c.fg, bg = config.transparent_background and "NONE" or c.bg },
  MsgSeparator = { fg = c.fg, bg = c.bg },
  NonText = { fg = c.gray },
  Normal = { fg = c.fg, bg = config.transparent_background and "NONE" or c.bg },
  NormalFloat = { bg = c.popup_back },
  NormalNC = { fg = c.fg, bg = config.transparent_background and "NONE" or c.bg },
  Number = { fg = c.blue },
  Operator = { fg = c.purple },
  Pmenu = { fg = c.light_gray, bg = c.popup_back },
  PmenuSel = { fg = c.dark, bg = c.blue },
  PmenuSbar = { bg = c.dark },
  PmenuThumb = { bg = c.gray },
  PreCondit = { fg = c.purple },
  PreProc = { fg = c.purple },
  Question = { fg = c.orange },
  QuickFixLine = { bg = c.dark },
  Repeat = { fg = c.purple, style = "bold" },
  Search = { fg = c.yellow, bg = c.dark },
  SignColumn = { bg = c.bg },
  Special = { fg = c.blue },
  SpecialChar = { fg = c.red },
  SpecialComment = { fg = c.gray, style = "italic" },
  SpecialKey = { fg = c.blue, style = "bold" },
  SpellBad = { fg = c.red, style = "underline" },
  SpellCap = { fg = c.yellow, style = "underline" },
  SpellLocal = { fg = c.green, style = "underline" },
  SpellRare = { fg = c.purple, style = "underline" },
  Statement = { fg = c.purple },
  StatusLine = { fg = c.dark },
  StatusLineNC = { fg = c.dark },
  StatusLineTerm = { fg = c.dark },
  StatusLineTermNC = { fg = c.dark },
  StorageClass = { fg = c.cyan },
  String = { fg = c.green },
  Structure = { fg = c.orange },
  Substitute = { fg = c.yellow, bg = c.dark },
  TabLine = { fg = c.light_gray, bg = c.dark },
  TabLineFill = { fg = c.fg, bg = c.dark },
  TabLineSel = { fg = c.fg, bg = c.dark },
  Tag = { fg = c.red },
  TermCursor = { fg = c.cursor_fg, bg = c.cursor_bg },
  TermCursorNC = { fg = c.cursor_fg, bg = c.cursor_bg },
  Title = { fg = c.blue, style = "bold" },
  Todo = { fg = c.yellow, bg = c.dark, style = "bold" },
  Type = { fg = c.blue },
  Typedef = { fg = c.purple },
  Variable = { fg = c.blue },
  VertSplit = { fg = c.dark, bg = c.dark },
  Visual = { bg = c.blue },
  VisualNOS = { bg = c.dark },
  WarningMsg = { fg = c.yellow, bg = c.dark },
  Whitespace = { fg = c.gray },
  WildMenu = { fg = c.dark, bg = c.blue },
}

return M
