local c = require("stardust.colors")
local config = require("stardust.config")

local M = {}

M.base = {
  -- Basic style definitions
  Bold = { style = "bold" },
  Italic = { style = "italic" },
  Underlined = { style = "underline" },

  -- Syntax groups with specific color settings
  Boolean = { fg = c.orange },
  Character = { fg = c.light_red, style = "bold" },
  ColorColumn = { bg = c.dark_gray },
  Comment = { fg = c.green, style = "italic" },
  Conceal = { fg = c.gray, bg = c.dark_gray },
  Conditional = { fg = c.yellow_orange, style = "bold" },
  Constant = { fg = c.yellow_orange, style = "bold" },
  Cursor = { fg = c.cursor_fg, bg = c.cyan },
  CursorColumn = { bg = c.dark_blue },
  CursorIM = { fg = c.cursor_fg, bg = c.cursor_bg },
  CursorLine = { bg = c.dark },
  CursorLineNr = { fg = c.context, bg = c.dark },
  Debug = { fg = c.light_red, style = "bold" },
  Define = { fg = c.orange, style = "bold" },
  Delimiter = { fg = c.gray },
  DiffAdd = { fg = c.green, bg = c.dark },
  DiffAdded = { fg = c.green },
  DiffChange = { bg = c.dark_gray, style = "underline" },
  DiffDelete = { fg = c.context, bg = c.light_red },
  DiffRemoved = { fg = c.diff_delete },
  DiffText = { fg = c.light_red, bg = c.dark_blue },
  DiffFile = { fg = c.cyan },
  DiffIndexLine = { fg = c.gray },
  Directory = { fg = c.blue, style = "bold" },
  EndOfBuffer = { fg = c.bg },
  Error = { fg = c.green, bg = c.bg, style = "bold" },
  ErrorMsg = { fg = c.green, bg = c.light_red, style = "bold" },
  Exception = { fg = c.magenta, style = "bold" },
  Float = { fg = c.orange },
  FloatBorder = { fg = c.gray, bg = c.dark },
  FoldColumn = { fg = c.green, bg = c.dark_gray },
  Folded = { fg = c.green, bg = c.dark_gray },
  Function = { fg = c.yellow_orange },
  Identifier = { fg = c.orange },
  Ignore = { fg = c.gray, bg = c.bg, style = "bold" },
  IncSearch = { fg = c.yellow, bg = c.green },
  Include = { fg = c.purple, style = "bold" },
  Keyword = { fg = c.yellow_orange, style = "bold" },
  Label = { fg = c.orange, style = "underline" },
  LineNr = { fg = c.gray },
  Macro = { fg = c.orange, style = "bold" },
  MatchParen = { fg = c.yellow, bg = c.green, style = "bold" },
  MatchParenCur = { style = "underline" },
  MatchWord = { style = "underline" },
  MatchWordCur = { style = "underline" },
  ModeMsg = { fg = c.orange },
  MoreMsg = { fg = c.white, style = "bold" },
  MsgArea = { fg = c.fg, bg = config.transparent_background and "NONE" or c.bg },
  MsgSeparator = { fg = c.fg, bg = c.bg },
  NonText = { fg = c.dark_gray, style = "bold" },
  Normal = { fg = c.fg, bg = c.bg },
  NormalFloat = { bg = c.dark },
  NormalNC = { fg = c.fg, bg = config.transparent_background and "NONE" or c.bg },
  Number = { fg = c.blue },
  Operator = { fg = c.white },
  Pmenu = { fg = c.light_gray, bg = c.popup_back },
  PmenuSbar = { bg = c.dark },
  PmenuSel = { fg = c.light_gray, bg = c.blue },
  PmenuThumb = { bg = c.gray },
  PreCondit = { fg = c.purple, style = "bold" },
  PreProc = { fg = c.orange, style = "bold" },
  Question = { fg = c.white, style = "bold" },
  QuickFixLine = { bg = c.dark_gray },
  Repeat = { fg = c.yellow_orange, style = "bold" },
  Search = { fg = c.yellow, bg = c.green },
  SignColumn = { bg = c.bg },
  Special = { fg = c.yellow_orange },
  SpecialChar = { fg = c.light_red, style = "bold" },
  SpecialComment = { fg = c.green, style = "bold" },
  SpecialKey = { fg = c.green },
  SpellBad = { fg = c.red },
  SpellCap = { fg = c.blue },
  SpellLocal = { fg = c.green },
  SpellRare = { fg = c.purple },
  Statement = { fg = c.yellow_orange },
  StatusLine = { fg = c.white, bg = c.dark_gray },
  StatusLineNC = { fg = c.gray, bg = c.dark_blue },
  StorageClass = { fg = c.magenta, style = "bold" },
  String = { fg = c.light_red },
  Structure = { fg = c.orange, style = "bold" },
  Substitute = { fg = c.light_gray, bg = c.orange },
  TabLine = { fg = c.green, bg = c.dark },
  TabLineFill = { fg = c.fg, bg = c.dark },
  TabLineSel = { fg = c.fg, bg = c.dark },
  Tag = { fg = c.red, style = "bold" },
  TermCursor = { fg = c.cursor_fg, bg = c.cursor_bg },
  TermCursorNC = { fg = c.cursor_fg, bg = c.cursor_bg },
  Title = { fg = c.white, style = "bold" },
  Todo = { fg = c.white, bg = c.bg, style = "bold" },
  Type = { fg = c.orange, style = "bold" },
  Typedef = { fg = c.orange, style = "bold" },
  Variable = { fg = c.cyan },
  VertSplit = { fg = c.bg, bg = c.dark },
  Visual = { bg = c.ui_blue },
  VisualNOS = { bg = c.dark },
  WarningMsg = { fg = c.white, bg = c.dark_gray },
  Whitespace = { fg = c.gray },
  WildMenu = { fg = c.green, bg = c.blue },
  lCursor = { fg = c.cursor_fg, bg = c.cursor_bg },
  -- Markdown
  markdownBlockquote = { fg = c.accent },
  markdownBold = { fg = c.yellow, style = "bold" },
  markdownCode = { fg = c.green },
  markdownCodeBlock = { fg = c.green },
  markdownCodeDelimiter = { fg = c.green },
  markdownH1 = { fg = c.blue },
  markdownH2 = { fg = c.blue },
  markdownH3 = { fg = c.blue },
  markdownH4 = { fg = c.blue },
  markdownH5 = { fg = c.blue },
  markdownH6 = { fg = c.blue },
  markdownHeadingDelimiter = { fg = c.blue },
  markdownHeadingRule = { fg = c.accent },
  markdownId = { fg = c.purple },
  markdownIdDeclaration = { fg = c.blue },
  markdownIdDelimiter = { fg = c.light_gray },
  markdownItalic = { style = "italic" },
  markdownLinkText = { fg = c.blue },
  markdownListMarker = { fg = c.red },
  markdownRule = { fg = c.accent },
  markdownUrl = { fg = c.cyan, style = "underline" },
}

return M
